### ISSUE TITLE
missing mime-core.lua

### ISSUE THREAD

**Issue by nelson2005** [duhoobo/lua-resty-smtp#17]
I installed lua-resty-smtp through opm, and when I use it I get

error: /openresty-1.11.2.2/site/lualib/resty/smtp/mime.lua:15: module 'resty.smtp.mime-core' not found:
        no field package.preload['resty.smtp.mime-core']
        no file '/openresty-1.11.2.2/site/lualib/resty/smtp/mime-core.lua'
...

it looks like mime-core.lua isn't anywhere on the system, not the least in the lualib/resty/smtp

s -l /openresty-1.11.2.2/site/lualib/resty/smtp/
total 40
-rw-rw-r-- 1 xxx hostapgp 4038 Feb  9 11:57 base64.lua
-rw-rw-r-- 1 xxx hostapgp 8224 Feb  9 11:57 ltn12.lua
drwxrwxr-x 2 xxx hostapgp 4096 Feb  9 11:57 mime
-rw-rw-r-- 1 xxx hostapgp 2796 Feb  9 16:43 mime.lua
-rw-rw-r-- 1 xxx hostapgp  615 Feb  9 11:57 misc.lua
-rw-rw-r-- 1 xxx hostapgp 6638 Feb  9 11:57 qp.lua
-rw-rw-r-- 1 xxx hostapgp 3444 Feb  9 11:57 tp.lua

Am I doing something wrong?  Or is it a packaging problem?

Thanks

**Comment by GUI** [comment]
I believe this was a packaging problem on OPM's end when lua-resty-smtp originally got uploaded to OPM. See https://github.com/openresty/opm/issues/33 (basically there was a bug with filenames that contained hyphens, and packages uploaded before November 6, 2016 were affected).

@duhoobo: If you re-upload the package to OPM now, that should fix the problem with OPM installations (you don't need to make any changes other than bumping the version and uploading the new version to OPM).

**Comment by nelson2005** [comment]
@GUI : thanks for the tip.  Very helpful.
@duhoobo : I'll close this now that the root cause is out there.

**Comment by stlnkm** [comment]
> [@GUI](https://github.com/GUI) : thanks for the tip. Very helpful. [@duhoobo](https://github.com/duhoobo) : I'll close this now that the root cause is out there.

作者似乎没有重新上传openresty，opm get问题仍然存在，请问您是怎么解决的呢？opm get后本地修改吗？谢谢！
