### ISSUE TITLE
socket does not have ssl support

### ISSUE THREAD

**Issue by robertzhouxh** [duhoobo/lua-resty-smtp#4]
Hi,

    I have chosen your  lua-resty-smtp lib to send email under openresty. But there is an issue that when call  smtp.send, there prompt the message ----- "socket does not have ssl support"

Dependeces: 
ngx_openresty-1.7.4.1rc2.tar.gz, 
lua5.2, 
luajit2.0,

How should i do to resolve the issue.

here is my code 

local ltn12 = require("resty.smtp.ltn12")
local mime = require("resty.smtp.mime")
local smtp = require("resty.smtp")
local socket = require("socket")
function sendmail()
    from= "<from@qq.com>"
    rcpt= {
        "<to@qq.com>"
    }

    mesgt = {
        headers= {
            subject = mime.ew("中文标题", nil, {}),
            ["content-transfer-encoding"] = "quoted-printable",
            ["content-type"] = "text/plain; charset='utf-8'",
        },

        body= mime.qp("中文内容，HELLO WORLD. "),
    }
    ngx.log(ngx.DEBUG, 'send email starting .....................')
    r, e = smtp.send {
        from= from,
        rcpt= rcpt,
        source= smtp.message(mesgt),
        server= "smtp.qq.com",
        user= "from@qq.com",
        password= "mypassword",
        --domain= "smtp.qq.com",
        port = 465,
        create= socket.tcp,
        ssl= { enable= true, verify_cert= false },
    }

    if not r then
        ngx.log(ngx.DEBUG, 'register end.....................' .. "send fail" .. e)
    else
        ngx.log(ngx.DEBUG, 'register end.....................' .. "send ok")
    end
end
sendmail()

thanks!

**Comment by duhoobo** [comment]
Please refer to commit [cbfc96c67690f6a28e132262127fef4595efd8a0](https://github.com/duhoobo/lua-resty-smtp/commit/cbfc96c67690f6a28e132262127fef4595efd8a0)
