### ISSUE TITLE
Is there any way to install resty-smtp directly from the net?

### ISSUE THREAD

**Issue by nelson2005** [duhoobo/lua-resty-smtp#7]
I tried
`luarocks install https://github.com/duhoobo/lua-resty-smtp/blob/master/rockspec/resty.smtp-0.0.3-1.rockspec`
which has worked for me for some other rocks (like MoonScript) but didn't have much luck

To clarify:  I tried using the luarocks method suggested on the project page
`luarocks install --local rockspec/resty.smtp-0.0.3-1.rockspec`
but it appears to use git, which isn't installed on the machine I'm using.

I understand that I can edit the makefile to point to my lua installation

**Comment by dizballanze** [comment]
Try: 
```
sudo luarocks install https://raw.githubusercontent.com/duhoobo/lua-resty-smtp/master/rockspec/resty.smtp-0.0.3-1.rockspec
```

**Comment by nelson2005** [comment]
Thanks, that rockspec has
```
-- contains information on how to fetch sources to build this rock.
source = {
    url= "git://github.com/duhoobo/lua-resty-smtp.git",
    file= "lua-resty-smtp"
}
```
I noted in the original post that I don't have git installed , so this method fails as well.

**Comment by nelson2005** [comment]
Thanks for packaging this on opm, I'm able to pull it directly from there  now
